/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Porsche911.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Porsche(props) {
  const { nodes, materials } = useGLTF('models/Porsche911.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry}>
      <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 || overlay==34 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.mirrors.geometry} material={materials.Body_paint_Jet_black} />
      <mesh geometry={nodes.Object_133.geometry} material={materials.Fabric} />
      <mesh geometry={nodes.Object_133_1.geometry} material={materials['Plastic_-_Glossy_Black']} />
      <mesh geometry={nodes.Object_133_2.geometry} material={materials['Metal_-_Chrome']} />
      <mesh geometry={nodes.Object_133_3.geometry} material={materials.Belt} />
      <mesh geometry={nodes.Object_133_4.geometry} material={materials.Rubber} />
      <mesh geometry={nodes.Object_133_5.geometry} material={materials['Plastic_-_Black']} />
      <mesh geometry={nodes.Object_133_6.geometry} material={materials.Fabric2} />
      <mesh geometry={nodes.Object_133_7.geometry} material={materials.Body_paint_Jet_black} />
      <mesh geometry={nodes.Object_133_8.geometry} material={materials.Structure} />
      <mesh geometry={nodes.Object_133_9.geometry} material={materials['Leather_-Dashboard']} />
      <mesh geometry={nodes.Object_133_10.geometry} material={materials.Dials_Glass} />
      <mesh geometry={nodes.Object_133_11.geometry} material={materials['Interior_Detail_-_No_transparent']} />
      <mesh geometry={nodes.Object_133_12.geometry} material={materials['Interior_Detail_-_Emissive']} />
      <mesh geometry={nodes.Object_133_13.geometry} material={materials.Grid} />
      <mesh geometry={nodes.Object_133_14.geometry} material={materials.Exhaust} />
      <mesh geometry={nodes.Object_133_15.geometry} material={materials.Window_Glass} />
      <mesh geometry={nodes.Object_133_16.geometry} material={materials.Lights} />
      <mesh geometry={nodes.Object_133_17.geometry} material={materials.Lights_2} />
      <mesh geometry={nodes.Object_133_18.geometry} material={materials.Interior_Detail} />
      <mesh geometry={nodes.Object_133_19.geometry} material={materials.Lights_Detail} />
      <mesh geometry={nodes.Object_133_20.geometry} material={materials.Logo} />
      <mesh geometry={nodes.Object_133_21.geometry} material={materials.Spekaer} />
      <mesh geometry={nodes.Object_133_22.geometry} material={materials.Stich} />
      <mesh geometry={nodes.Object_133_23.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_133_24.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_133_25.geometry} material={materials['Leather_-_Dot_Pattern']} />
      <mesh geometry={nodes.Object_133_26.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Object_133_27.geometry} material={materials.Tail_light_glass} />
      <mesh geometry={nodes.Object_133_28.geometry} material={materials['Body_Paint_-_Jet_Black']} />
      <mesh geometry={nodes.Object_133_29.geometry} material={materials.Window_Glass_not_transparent} />
      <mesh geometry={nodes.Object_133_30.geometry} material={materials['Metal_-_Black']} />
      <mesh geometry={nodes.Object_133_31.geometry} material={materials.Tyre} />
      <mesh geometry={nodes.Object_133_32.geometry} material={materials.Caliper_Detail} />
      <mesh geometry={nodes.Object_133_33.geometry} material={materials.Rotor} />
      <mesh geometry={nodes.Object_133_34.geometry} material={materials.Caliper} />
    </group>
  )
}

useGLTF.preload('/Porsche911.glb')
