/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Porsche911.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { proxy, useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Porsche(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Porsche911.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.mirrors.geometry} material={materials.Body_paint_Jet_black} />
      <mesh geometry={nodes.body001.geometry} material={materials['Slaughter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.body006.geometry} material={materials['SpiderID.001']} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.body009.geometry} material={materials['Mayan.001']} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.body010.geometry} material={materials['SeaBreeze.001']} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.body011.geometry} material={materials['ShapeShifter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.body012.geometry} material={materials['Silk.001']} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.body013.geometry} material={materials['SnakeSkin.001']} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.body016.geometry} material={materials['TopGun.001']} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.body018.geometry} material={materials['WildWest.001']} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.body019.geometry} material={materials['Zombie.001']} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      <mesh geometry={nodes.Object_133.geometry} material={materials.Fabric} />
      <mesh geometry={nodes.Object_133_1.geometry} material={materials['Plastic_-_Glossy_Black']} />
      <mesh geometry={nodes.Object_133_2.geometry} material={materials['Metal_-_Chrome']} />
      <mesh geometry={nodes.Object_133_3.geometry} material={materials.Belt} />
      <mesh geometry={nodes.Object_133_4.geometry} material={materials.Rubber} />
      <mesh geometry={nodes.Object_133_5.geometry} material={materials['Plastic_-_Black']} />
      <mesh geometry={nodes.Object_133_6.geometry} material={materials.Fabric2} />
      <mesh geometry={nodes.Object_133_7.geometry} material={materials.Body_paint_Jet_black} />
      <mesh geometry={nodes.Object_133_8.geometry} material={materials.Structure} />
      <mesh geometry={nodes.Object_133_9.geometry} material={materials['Leather_-Dashboard']} />
      <mesh geometry={nodes.Object_133_10.geometry} material={materials.Dials_Glass} />
      <mesh geometry={nodes.Object_133_11.geometry} material={materials['Interior_Detail_-_No_transparent']} />
      <mesh geometry={nodes.Object_133_12.geometry} material={materials['Interior_Detail_-_Emissive']} />
      <mesh geometry={nodes.Object_133_13.geometry} material={materials.Grid} />
      <mesh geometry={nodes.Object_133_14.geometry} material={materials.Exhaust} />
      <mesh geometry={nodes.Object_133_15.geometry} material={materials.Window_Glass} />
      <mesh geometry={nodes.Object_133_16.geometry} material={materials.Lights} />
      <mesh geometry={nodes.Object_133_17.geometry} material={materials.Lights_2} />
      <mesh geometry={nodes.Object_133_18.geometry} material={materials.Interior_Detail} />
      <mesh geometry={nodes.Object_133_19.geometry} material={materials.Lights_Detail} />
      <mesh geometry={nodes.Object_133_20.geometry} material={materials.Logo} />
      <mesh geometry={nodes.Object_133_21.geometry} material={materials.Spekaer} />
      <mesh geometry={nodes.Object_133_22.geometry} material={materials.Stich} />
      <mesh geometry={nodes.Object_133_23.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_133_24.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_133_25.geometry} material={materials['Leather_-_Dot_Pattern']} />
      <mesh geometry={nodes.Object_133_26.geometry} material={materials.Aluminum} />
      <mesh geometry={nodes.Object_133_27.geometry} material={materials.Tail_light_glass} />
      <mesh geometry={nodes.Object_133_28.geometry} material={materials['Body_Paint_-_Jet_Black']} />
      <mesh geometry={nodes.Object_133_29.geometry} material={materials.Window_Glass_not_transparent} />
      <mesh geometry={nodes.Object_133_30.geometry} material={materials['Metal_-_Black']} />
      <mesh geometry={nodes.Object_133_31.geometry} material={materials.Tyre} />
      <mesh geometry={nodes.Object_133_32.geometry} material={materials.Caliper_Detail} />
      <mesh geometry={nodes.Object_133_33.geometry} material={materials.Rotor} />
      <mesh geometry={nodes.Object_133_34.geometry} material={materials.Caliper} />
    </group>
  )
}

useGLTF.preload('/models/Porsche911.glb')
